apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: amazon
  name: amazon
  namespace: kiran
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amazon
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: amazon
    spec:
      containers:
      - image: kiran023/amazon:v1
        name: amazon
        ports:
        - containerPort: 8080
        resources: {}
status: {}
