apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    batch.kubernetes.io/job-tracking: ""
  creationTimestamp: "2023-08-29T17:36:11Z"
  generation: 1
  labels:
    batch.kubernetes.io/controller-uid: 21b8762e-c072-45c0-823f-0b2ebc376d07
    batch.kubernetes.io/job-name: javajob
    controller-uid: 21b8762e-c072-45c0-823f-0b2ebc376d07
    job-name: javajob
  name: javajob
  namespace: default
  resourceVersion: "23559"
  uid: 21b8762e-c072-45c0-823f-0b2ebc376d07
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: 21b8762e-c072-45c0-823f-0b2ebc376d07
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        batch.kubernetes.io/controller-uid: 21b8762e-c072-45c0-823f-0b2ebc376d07
        batch.kubernetes.io/job-name: javajob
        controller-uid: 21b8762e-c072-45c0-823f-0b2ebc376d07
        job-name: javajob
    spec:
      containers:
      - image: kiran023/java
        imagePullPolicy: Always
        name: javajob
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
