apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    batch.kubernetes.io/job-tracking: ""
  creationTimestamp: "2023-08-28T18:39:47Z"
  generation: 1
  labels:
    batch.kubernetes.io/controller-uid: aa765e2d-1a73-434e-ba7b-db79f6acdd11
    batch.kubernetes.io/job-name: java
    controller-uid: aa765e2d-1a73-434e-ba7b-db79f6acdd11
    job-name: java
  name: java
  namespace: default
  resourceVersion: "22699"
  uid: aa765e2d-1a73-434e-ba7b-db79f6acdd11
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: aa765e2d-1a73-434e-ba7b-db79f6acdd11
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        batch.kubernetes.io/controller-uid: aa765e2d-1a73-434e-ba7b-db79f6acdd11
        batch.kubernetes.io/job-name: java
        controller-uid: aa765e2d-1a73-434e-ba7b-db79f6acdd11
        job-name: java
    spec:
      containers:
      - image: kiran023/java
        imagePullPolicy: Always
        name: java
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
